name: syncToGitee
on:
  push:
    branches:
      - blog-stand
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/zdmyzhz'
          dst: 'gitee/zdmyzhz'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "vuepress-blog"
          force_update: true
          debug: true
